import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "A D M I N | Tharisha Perera",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>{children}</main>
  );
}
